export const ScreenNames = {
  Home: 'Home',
  Saved: 'Saved',
  Profile: 'Profile',
  Booking: 'Booking',
  MainTabBar: 'MainTabBar',
  Login: 'Login',
  Register: 'Register',
  UpdateProfile: 'UpdateProfile',
  ParkingDetail: 'ParkingDetail',
  NotificationSettings: 'NotificationSettings',
  Security: 'Security',
  BookParking: 'BookParking',
  Payment: 'Payment',
  ReviewSummary: 'ReviewSummary',
  ParkingTicket: 'ParkingTicket',
  SelectVehicle: 'SelectVehicle',
  Direction: 'Direction',
  RouteNavigation: 'RouteNavigation',
  ParkingTimer: 'ParkingTimer',
};
